travis:
  secure:
    BINSTAR_TOKEN: Ac2e9rU1IGzPPTiT52wjlYa+Ls7CEXdhuHOwalnXZ7Wynpa4hEN++jW+OmK4+7/afufnSmW4wVGF/9/aZo4nwZE5yJer1NaumKahn1pErCfnR9EVHxy3UcGBoLKOej4On4E3n+kzKfwkjaMDbDbESPsCC0jRJhRgoElrPR/1PF+JH/KaXX38jk5Spi3CmxNbqhtVXP8NyYEI2BSy8nhWvNNxmADsjAS5HetrYrOZkcnqnUbmQZggvRZ75y917MC6R8vwmMsHeUG1nW1LwHXxToYuTe0qfasYawuFi4QmqCnU02bQg1Ep65FXr+z77QsEeCx+M7WOrcpikSoAKkw6noPTAXQqYbWp6ZrbcT4ZeouIe7X8XczmAuyE3Eb7rbGagWFXsx1BazFkBpeiPU8aEVix/lvTav3LgtZ0hR5Ujr784PEnkOuH/3q5BZdxv+eo61E6clm9TWik0jZHxg9LgeMtUqk3gObOnc2Bb0/ZzBtb+2vRb98jGUU26wLzfhPFRZtOGX4fWhFZ+ZlaUbY1JPjXEGxrygq6dmSoU+g9oR4EeYyDVhIpFL7gjx0w+Ot4nYeL8+PZ4UH4rJVwnmPC2xUmtDiYMY/1vTF0DbLaUDNAORQBjj997XhGGDnV8JTPip864UDy9zA95L8ifve0D79tWYvORkiADJ9RHM7+xuE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
