travis:
  secure:
    BINSTAR_TOKEN: gMQOD6E/jqf2mbZoMW7zOYkfFkRRqL0wEj+AM+C6xTfGGXOS0PH0w2GB0QcSmjbi/niQGCxR2bkM8VQ0paKb7Uj29HDgw5OcyDGRf4hcTwgf+NaUqTaQiVXbhEG17gJojbAtU4rDZ7VAgfoG/0yD1VQ/X2iCQMTnp7TxRXCwTXpIwBh4E3i9tJDez2/UAM4jW8VQdFIcEVfM8j7XqyMPq2eAv25R3+xuaS7y95FeVqK9swXoQsy+EKsY5JDe680wfgbkcJAZGYKPTd2TyBEY4UGVOCc/KPcQhMyBBE7KN3cHckkf2EnLKKTF2BDyZvSnfANRDH1ODF2AltNocyyxKijPmx0HytuU/A7XZypSXzxns+cgyCKC1CCBp4Gsr8vy9xwYPHFOCK/JrnbYH6MDPoHSgtctoSJ3R/kirhIxF3PcGeaxl4I/uDo4kId42yjhAul477CdyTYNMGS5EuKUTt3jO503CpD9Fa+uphurZuNfTDpP0d/Q+abC5hTABR+KFQDoZzl+bBS/54Eolft6YvH3G9YTXPuKJiuMTpd+fxUQrW1GSxHy8I4Q+P6mUCbB/N70JRh6R4uGUqAuIxMhtUkJkZ7HcQzb1tUzhvFR8g36QnL6KxnukHMkuOssm+Wan9KvmPvbbVnwKa9B+Fb3a2DMpTHK7KTzM8SAeB/VLS4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
