travis:
  secure:
    BINSTAR_TOKEN: 0fIBCB52BLlvKiJ6nd4lv3Xcyi0unLgX2TdZ1Wgxs8xAlMjCIJ5iyJts8SXO2gmKhD7O7pMcXZf+48qO/RCMeNAtN0ZZdnR99Oq6y5auZJHWePMfzZkCG4zB6EWEYxyVYH1cGnXpmOpS/HBkOrfGIhqrUH9s2WZYvMgRYM4ZVp8kVMfFSaiD2PgL94cuk5h2ti0y1kxcbZMe/jT79oaa0Z39ca8f6auqqH2NBS7bPPsuhwoyNRgxVWLyaT+piMKe2m7IP78Ye4Cm1pQT43GSuagIF9GL1Ig+AlkEOL3tQQHra1flsJyze+dHVvglAKjzJj3PacITe/1ajv6Gs6M1EYdXDWvkZMQR78Z23LNvPq5BOfARspEEHRZIpP40SXKA8ZE1pveXfmaRUVsuz9NWnyKHDy6X6VwzIC3RTwI98GlYy441MrK1c/Qqc6rYrAAXlquDMgYedd0WjkcDHuwB9BC575Lq68/b8ozTvGo31bFh5iLTnzzWTph0xQbodu0pai7650siedbJH6xUwoLtkWVnl5WMdtjvHJ4YVJ/xbg0gwRlhuRh804MSnksoi9V9mUfnMqaVsBukrJxdnYILlZ/zXtcoKpXP5uZIQDltcJYXPY0sIrslZQbUfE3FNodXuw1In9tTeb6O+gPchuRcWhKUIR7WmIVHGZ4R2+EUTGI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
