travis:
  secure:
    BINSTAR_TOKEN: kbWXCSVo0YB/OUTld4wwfARSgihLPDSKJ8arwZBzcLM6ZHNm6+SXa0Y2IU9SLC5pyyicZbN2vxuDWgi0MKdLsYWwfDHo0bmJi3Gv8tvmGzJXYpViXOfubHv5cQcGJrUZ75JpW/FicdmsGYhKVGwY1As0ucJW0ZfF9m9m3xDMrmWuEkM+iRjrirDxbbAsoK0e0r1HdEFk/4KiWwXqqNYiu16PJm/pN7SyuQbKwN0BH7Yu70yXBrMCPcz0ZNitBOZOb37vbmGlI00lKB4jD+E0mj+J1/c47h71qaK0ApAQyqAMgaueo5uqQrQwK0A7dTRgkP3Nlw/xFKsbEBbmgH6cFXV5FyOLcGy2SRLM62HwOiwnDqtjCK5Nbe/Gupqz65+tfP7O8EtAK9vRx3FYK044dIsG4W5qRI1eWfcsvztiuzbumpLJz2KdReZPQRTOIKS/eY/FpXnK5elepJH2XtAnPPzf+6Vcfrzl+ypLfcNFaY9cVWSBIYHeHkyQvxpvJVvKN0PgH2P/Yn+AcMV+PMNDx9+k3JymUtUVk77ju0q064Hzn4gy7GsCpumTfZebzmKWZnlGI8M9gJ55UpTYlabYJxjT/hLiUwZTZHZk+UZ7YjImPKVp5DZsGDoZYJhCSKyxDHRP9MruWqTomI28u/bTYgWwx7fTtFDBXRVZdgnQCY0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
