travis:
  secure:
    BINSTAR_TOKEN: 2yhh2c2zXZcLLN5hDlWeiS3LQXNmxP1194kbCcQnhPJXxAJteQSdS8Gx1XBlkx69S1ENa6LA1E4TR/OS33bEctYjQN2KHkw1Jm7k84pnJe9EuYalrtnBuzKoykr19OO0U8QYU8xCc6mBRWa2EBKJ+I3We2S6zyl0UBLGvapiArVwP+tB3YE6DGnQ8wacynOuzhnGlHS6zqs4fGgCYxABuAR2CaTOCFgjJIw7lP6a4bR855nFBmgDrW0Cyxe7UMB4Y/66DFmbIaLBaQtgdOhia0S6s/kPS5Rrah7wyZWL5Mm6PB57C2kKt8FRRBBXO7AAqgEbbPXb5WU0WpKuJy0alqlJmQL/WNJqJmmifi/6SVs5PAb9IQeV//ZE4DA4VGqa/RJAjfbdH5xnjdY7MFmz2cQeNKsDXxyBjfVQaECxO28ISOQ9vtMVjj9gg3/p5bKu1VPCc4VRbD+/qT3s211RI+034DH64qbJmhs7zudFozteOBkStYT9Mb9WWAmtogyg5oCwjd/QdRuzNYmXkYFny7JGu+sdMkMwygkveHJurbga+51cn6YZM1OS43pvADSQbVRp3u7o4pmCRd47qoGlk/bocLBu3rVhe08AZ1qM17Ak24lz6kBmFQqm9xsRXHTc9ypiAb9ES/19+QnB2r5OpDEsdesn6FuWkfPoIin0iUM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
